spring:
  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: ${OAUTH2_YANDEX_CLIENT_ID}
            client-secret: ${OAUTH2_YANDEX_CLIENT_SECRET}
            client-name: Yandex
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/yandex
            scope:
              - login:email
              - login:info
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: id
