package com.pxdkxvan.auth.response;

import com.fasterxml.jackson.annotation.JsonValue;

import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum ResponseCode {

    // 2XX SUCCESS
    ACCOUNT_CREATED("SUCCESS_ACCOUNT_CREATED"),
    ACCOUNT_VERIFIED("SUCCESS_ACCOUNT_VERIFIED"),
    ACCOUNT_LOGGED_IN("SUCCESS_ACCOUNT_LOGGED_IN"),
    ACCOUNT_LOGGED_OUT("SUCCESS_ACCOUNT_LOGGED_OUT"),
    TOKEN_REFRESHED("SUCCESS_TOKEN_REFRESHED"),
    VERIFICATION_EMAIL_SENT("SUCCESS_VERIFICATION_EMAIL_SENT"),

    // 4XX CLIENT ERROR
    VALIDATION_FAILED("ERR_VALIDATION_FAILED"),
    EMAIL_ALREADY_TAKEN("ERR_EMAIL_ALREADY_TAKEN"),
    USERNAME_ALREADY_TAKEN("ERR_USERNAME_ALREADY_TAKEN"),
    LOGIN_NOT_FOUND("ERR_LOGIN_NOT_FOUND"),
    PASSWORD_MISMATCH("ERR_PASSWORD_MISMATCH"),
    LOGIN_FAILED("ERR_LOGIN_FAILED"),
    ACCOUNT_NOT_VERIFIED("ERR_ACCOUNT_NOT_VERIFIED"),
    MISSING_REFRESH_TOKEN("ERR_MISSING_REFRESH_TOKEN"),
    TOKEN_NOT_FOUND("ERR_TOKEN_NOT_FOUND"),
    TOKEN_MALFORMED("ERR_TOKEN_MALFORMED"),
    TOKEN_DECODING_INVALID("ERR_TOKEN_DECODING_INVALID"),
    TOKEN_HEADER_INVALID("ERR_TOKEN_HEADER_INVALID"),
    TOKEN_SIGNATURE_INVALID("ERR_TOKEN_SIGNATURE_INVALID"),
    TOKEN_VALIDATION_NOT_PASSED("ERR_TOKEN_VALIDATION_NOT_PASSED"),
    VERIFICATION_FAILED("ERR_VERIFICATION_FAILED"),
    OAUTH2_AUTHENTICATION_ERROR("ERR_OAUTH2_AUTHENTICATION_ERROR"),
    OAUTH2_PROVIDER_NOT_SUPPORTED("ERR_OAUTH2_PROVIDER_NOT_SUPPORTED"),

    // 5XX SERVER ERROR
    ROLE_NOT_FOUND("ERR_ROLE_NOT_FOUND"),
    ACCOUNT_NOT_FOUND("ERR_ACCOUNT_NOT_FOUND"),
    EMAIL_SENDING_ERROR("ERR_EMAIL_SENDING_ERROR"),
    INTERNAL_SERVER_ERROR("ERR_INTERNAL_SERVER_ERROR");

    @JsonValue
    private final String code;

}
